### ISSUE TITLE
Filter graph doesn't have any filter chains. Can't create CLI command. If you want to make a direct copy of an asset, you'll need a different tool.

### ISSUE THREAD

**Issue by tgrushka** [Flutter-Bounty-Hunters/ffmpeg_cli#7]
Is there any way the filterGraph could be nullable, or if filterGraph.chains.isEmpty, that it could just not add the filter chains arguments to the command?

**Comment by Thomasssb1** [comment]
Added to my PR as well as more QOL features #9

**Comment by matthew-carroll** [comment]
I believe that this issue was resolved by #9. Please re-open if the issue persists.
